maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 220)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 128)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 128)
basic.pause(400)
let botLight = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 0)
while (true) {
    botLight.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(500)
    botLight.setPixelColor(0, neopixel.colors(NeoPixelColors.Indigo))
    botLight.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
    botLight.setPixelColor(2, neopixel.colors(NeoPixelColors.Blue))
    botLight.setPixelColor(3, neopixel.colors(NeoPixelColors.Violet))
    botLight.show()
}
